### ISSUE TITLE
Add external triggers

### ISSUE THREAD

**Issue by skibitsky** [drgrib/alfred-bear#14]
Hi,

Thank you for the great workflow! Since I use it a lot, I added an external trigger to the search action to be able to call it from [karabiner](https://github.com/pqrs-org/Karabiner-Elements) via Apple Script. However, every time I update the workflow, triggers are removed. May you add them, please?

<img width="1071" alt="CleanShot 2020-03-08 at 11 00 57@2x" src="https://user-images.githubusercontent.com/15127974/76159823-e9f7ae00-612c-11ea-940f-b574900a92c4.png">

**Comment by drgrib** [comment]
I don't have a problem doing this if the code inside is consistent and universal. Right now, it is filled with

> tell application id "com.runningwithcrayons.Alfred" to run trigger "search bear" in workflow "com.drgrib.bear" with argument "test"

Which doesn't sound right. What does yours contain?

**Comment by skibitsky** [comment]
It can be same as yours but without test argument:
```AppleScript
tell application id "com.runningwithcrayons.Alfred" 
to run trigger "search bear" in workflow "com.drgrib.bear"
```

You just create an external trigger and it will always work unless you change workflow's Bundle Id

For the reference, there is [alfred-spotify-mini-player](https://github.com/vdesabou/alfred-spotify-mini-player) workflow that has lots of external triggers.

**Comment by drgrib** [comment]
Added in #16

**Comment by skibitsky** [comment]
Thanks!
