### ISSUE TITLE
Feature Request -  Append to Note

### ISSUE THREAD

**Issue by nickwild-999** [drgrib/alfred-bear#19]
Hi thanks for the great workflow!

I'd like to append to a bullet MD list on a note (or ideally different notes ) do you have any plans to add anything like this to your roadmap?

**Comment by drgrib** [comment]
Can you give me an example of what that syntax would look like? I'm having trouble imagining how that would work.

**Comment by nickwild-999** [comment]
Hi,
I use the Alfred Drafts workflow and it works really well in this respect. 

[Drafts Workflow](https://forums.getdrafts.com/t/swipe-my-alfred-workflow-for-drafts-for-mac/3949) 

It would be great if you could replicate something similar ideally with the ability to have a couple of different lists

**Comment by drgrib** [comment]
I took a look but it is still not clear to me what syntax you could use to both specify a note title and specify a bullet, especially onto different notes. It looks like the workflow you linked to just appends everything to a single unnamed document.

How would that work?

**Comment by nickwild-999** [comment]
I think something like `badd    note-name    note-content` would work best. 

There would obviously have to be a means of setting up the UUID for that note (happy to be in the back end of the workflow) and it would be great to have the ability to have multiple notes (again personally I would be happy to duplicate accordingly in the workflow and replace the UUID)

Thanks

EDIT: I am happy for this just to append, but I'm sure there are many use cases for prepend functionality too

**Comment by drgrib** [comment]
That possible syntax had already occurred to me. But the problem I don't think you are seeing is that it is ambiguous. If you enter

```
badd quick brown fox jumps over the lazy dog
```

The system can't know know if you are adding:
- `brown fox jumps over the lazy dog` to  note `quick`
- `fox jumps over the lazy dog` to  note `quick brown`
- `jumps over the lazy dog` to  note `quick brown fox`
- `over the lazy dog` to  note `quick brown fox jumps`
- `the lazy dog` to  note `quick brown fox jumps over`
- `lazy dog` to  note `quick brown fox jumps over the`
...

If you have any two notes with overlapping names in those note title possibilities, there is literally no way to disambiguate. Further still if you allow `badd` to create new notes. And I can't even begin to imagine an unambiguous syntax for adding bullets to multiple notes.

**Comment by nickwild-999** [comment]
I think it could work with a delineator like a `|` for example. From my use case as I mentioned before I don't this would be adding to every available note, but just to be able to add to one or two notes like a todo list and another bulleted list

**Comment by drgrib** [comment]
I think this type of feature is out of scope for this workflow. I suggest creating a new workflow, possibly collaborating with the author of #20.
