### ISSUE TITLE
Question: sqlite is returning query string instead of row data

### ISSUE THREAD

**Issue by qhkm** [drgrib/alfred-bear#22]
Hello @drgrib, first of all thanks for this awesome alfred workflow, been using it extensively for my note taking flow!🙂

One quick question, i'm trying to run the seach function from cmd line but sqlite is not returning the title of the data from the query, but returning the query string instead and i'm not sure what's the problem here. Do you have any idea? Heres where i put some print to see the output.
 
![Screen Shot 2020-05-09 at 5 26 26](https://user-images.githubusercontent.com/25919652/81447034-d90ffb00-91b6-11ea-8787-4f165df3b126.png)
![Screen Shot 2020-05-09 at 5 27 39](https://user-images.githubusercontent.com/25919652/81447044-dd3c1880-91b6-11ea-9466-b2f79b9dba5b.png)

**Comment by drgrib** [comment]
Glad you are enjoying the workflow. Unfortunately, this isn't enough context for me to understand what you mean by "run the seach function from cmd line".

**Comment by drgrib** [comment]
So you mean run the `cmd/search/main.go`. My guess is you are using `go mod`? Something about the versioning of the repo or other repos I'm importing doesn't work with `mod`. I haven't debugged it yet. But I would try it without `mod` and it might work.

**Comment by qhkm** [comment]
Thanks for your response! Sorry! My bad for not providing enough context for you to understand what i meant.

Yes, what i meant is i tried to run from `cmd/search/main.go`. Regarding your question, i guess I did'nt run any `go mod init` command yet so i think go mod is not setup yet? By the way, go version is `1.12.1` and i dont know if this version of go will search for the gomod anywhere and set it up in the dir.

I also tried to change to go version 1.10.8 (to try to run it without `gomod`) and run the same command  `cmd/search/main.go` in GOPATH mode but it still returns the query string. I check the code and there's one part that i think might relates to this.

*`Query method in db/db.go`*
![Screen Shot 2020-05-09 at 16 34 14](https://user-images.githubusercontent.com/25919652/81467328-f1adfe80-9212-11ea-9446-d18b85bc3efd.png)

From this code above i can see that there`s `m` variable that stores that map of the column name. I think this is the part that is somehow related.

**Comment by drgrib** [comment]
I don't think the code has any problems. If that were the case then the workflow itself wouldn't function which obviously isn't the case since I use it every day and it has been downloaded over 200 times.

The issue is almost certainly your Go environment and how you are running it. I definitely won't be changing any code for your local run issues, so I would focus on how you are trying to run it.

**Comment by qhkm** [comment]
Yeah i think there must be something wrong with my go env. Do you mind to explain how did you run it? Thanks!!

**Comment by drgrib** [comment]
I'm running `go version go1.13.4 darwin/amd64` (macOS). I have a standard `GOPATH` set up with the project inside it under `src/github.com/drgrib/alfred-bear`. 

To build `cmd/search`, I `cd` to the directory and type `go build`. This creates the executable `search` which is called by the Bear workflow. It can be run from the command line in its directory using `./search ` followed by search terms which will create a JSON list of Alfred items matching the query. The same list is used by Alfred in the `bs` / `bsearch` script filter.

**Comment by drgrib** [comment]
I would make sure that you can run standard simple Go programs, create executables from them, and run the executables from the command line before attempting to build the `alfred-bear` executables. Some sources would be from https://golang.org/ or other Go tutorials.

**Comment by drgrib** [comment]
Good news: while trying to get `go.mod` working, I discovered that the package `"github.com/mattn/go-sqlite3"` I had been using had updated one of its data structures and broken my db code on fresh installs. The only reason my local repo was building the right code was because I had the old version.

Once I merge the branch I'm working on today into `master`, you should be able to pull the changes and run the code. You were right that the database code was the source of the issue.

**Comment by drgrib** [comment]
You should be good to go with #23.

**Comment by qhkm** [comment]
Glad to got it fixed!! Thanks so much
