### ISSUE TITLE
Open note in main window

### ISSUE THREAD

**Issue by tiwood** [drgrib/alfred-bear#24]
Hi @drgrib, 

Thanks for creating this great workflow!

Is it possible to open the notes in the `main window` instead of a new `pop-up`?

**Comment by Icecubelegacy** [comment]
@tiwood I was looking for the same thing.
You can open notes in the main window by going to the workflow folder
1. open info.plist
2. findall "new_window=yes"
3. Replace with new_window=no"
4. Save and try open a note with alfred.

It should open in the main window~

**Comment by drgrib** [comment]
Added in #25 and documented here:
https://github.com/drgrib/alfred-bear#open-note-in-bear-app

**Comment by adiachenko** [comment]
@drgrib Should have been the default IMO. The existing behavior looks very odd (at least for me on Big Sur). It opens Bear main window with searched/new note window superimposed on top of it. Ended up editing info.plist.

**Comment by drgrib** [comment]
@adiachenko We just have a difference in personal taste, I guess. I don't like having the entire massive Bear window opening when I'm creating or accessing an individual note. The context of many unrelated notes coming into context is distracting and heavy for my workflow. As the primary user and curator of the workflow offering to share and maintain it for free for others, I'm afraid I'm not willing to sacrifice my own workflow for requests from other users.

**Comment by adiachenko** [comment]
@drgrib It makes sense, if only it worked for me as you have described here 😂. 

Right now on my machine, `bsearch` and `bnew` open both Bear main window and a separate window with a note sitting on top of it. Running Big Sur, Alfred 4 and latest version of the workflow as linked in Readme.

Not sure if I am the odd on and whether I should open new issue. I guess I need to dig more into what's going on here.

**Comment by drgrib** [comment]
@adiachenko Interesting. My work has indefinitely asked us not to upgrade to Big Sur. Sounds like I need to so I can debug this. Do you leave Bear open or quit it every time you access it? I always leave Bear open on Catalina and only have the main window open the first time I launch the workflow after quitting Bear, usually because of a system restart.

**Comment by adiachenko** [comment]
> Do you leave Bear open or quit it every time you access it? 

I tried it both ways. Same result.

**Comment by drgrib** [comment]
@adiachenko I see. I'll have to install Big Sur and look into this after I've dealt with any general fallout from the upgrade.

**Comment by mjknght** [comment]
I can confirm that odd behaviour, since installing Big Sur. Strange!

**Comment by drgrib** [comment]
So I just installed Big Sur and I'm not able to reproduce this behavior. In my new Big Sur installation, notes open in a separate window without opening the main window, the same behavior as in Catalina.
