### ISSUE TITLE
Nit: I think you forgot to bump info.plist for v1.1.4

### ISSUE THREAD

**Issue by zahanm** [drgrib/alfred-bear#27]
TSIA
(noticed when importing the `.workflow` into Alfred)

**Comment by drgrib** [comment]
Strange. Do you know whether I need to manually update the field in the `.plist` or fill it out in the Alfred UI somewhere?

**Comment by zahanm** [comment]
https://github.com/drgrib/alfred-bear/commit/c5077c1c3e28bd722cdc4f80c62c82db701559fb

I think it's just in the repo, but not sure if there's Alfred UI to update it.

**Comment by drgrib** [comment]
Yeah. I for sure didn't make that update to the `.plist` manually. I'll be sure to use the UI to set it to the right version in an update I'm doing this week.

**Comment by drgrib** [comment]
Updated in #28.
