### ISSUE TITLE
Paste from Clipboard should be an option

### ISSUE THREAD

**Issue by ian-vu** [drgrib/alfred-bear#3]
By default anything in the clipboard is copied to a new note. Could this be a feature which can be toggled on an off?

**Comment by drgrib** [comment]
Agreed. I've been annoying myself with that feature for months. Changed in https://github.com/drgrib/alfred-bear/commit/c89e0d46023f1bc425f9f07c5f72893a1662a173. New release can be downloaded [here](https://github.com/drgrib/alfred-bear/releases/download/1.0.1/Bear.alfredworkflow).
