### ISSUE TITLE
[Request] Block to Search

### ISSUE THREAD

**Issue by spearkkk** [drgrib/alfred-bear#38]
Hello, Thank you for your nice share.

I'm trying to use this workflow.
It  is so amzaing and awesome!!.
But I want to a feature for searching..

Could I filter search reasult with tag?

I mean, 
There are notes with `#test` tag, but I don`t want to find these notes using workflow.

Would you have any plan for this feature?
Thank you!!

**Comment by drgrib** [comment]
Glad you are enjoying the workflow.

So just so I am understanding: you would like a filter to exclude notes with a certain tag? It's not something I've ever needed to do, so I can't guarantee it is something I would be able to put time into.

I'm also not sure what an intuitive syntax would be for that. Any thoughts?

**Comment by drgrib** [comment]
Looks like #37 is an identical request, so feel free to watch that issue and I'll close this one.

**Comment by spearkkk** [comment]
@drgrib Thank you !!!
