### ISSUE TITLE
'bs' stops working after update

### ISSUE THREAD

**Issue by prc1212** [drgrib/alfred-bear#43]
I just updated from 1.1.2 to 1.1.8 and one of the three alfred-bear commands stopped working.

bn and bcs both work fine but bs/bsearch comes up with nothing.
<img width="1064" alt="image" src="https://user-images.githubusercontent.com/64705985/122580545-5bbfe680-d056-11eb-83e8-f360989fb969.png">

There were some issues with the security certificate the first few times I tried it. I don't know if I can get the workflow to reindex or something like that.

**Comment by drgrib** [comment]
Unfortunately, I can't reproduce the issue. `bs` works fine for me. I'll need more information to debug. If `bcs` is working fine, then perhaps it is the security issue. I would try running the [new **Authorize All Executables** security command in the README](https://github.com/drgrib/alfred-bear#authorize-all-executables).

**Comment by prc1212** [comment]
Thanks, I was able to fix this by reinstalling and going through the security steps you mention! It's a great workflow.

**Comment by drgrib** [comment]
Glad to hear it!
