### ISSUE TITLE
Request: open notes in main Bear window

### ISSUE THREAD

**Issue by kimaldis** [drgrib/alfred-bear#46]
At the moment notes are opened in a new Bear window. Would it be possible for them to be opened in the main Bear window. As an option would be fine.

thanks.

**Comment by drgrib** [comment]
You can do this by holding the command key before pressing enter:
https://github.com/drgrib/alfred-bear#open-note-in-bear-app

**Comment by bheltzel** [comment]
Is there any way to make this a setting/preference? Or just to edit within the workflow. Thank you!

**Comment by drgrib** [comment]
Unfortunately, Alfred provides no way to make this configurable aside from editing the workflow yourself.
