### ISSUE TITLE
Code 127: /bin/bash: cmd/search/search: No such file or directory

### ISSUE THREAD

**Issue by crsantos** [drgrib/alfred-bear#5]
Hi, I need some help here.

Not sure if this is due to using Catalina, or do I need some go setup, but I'm getting this error (debugging this workflow):

`|[08:46:32.669] ERROR: Bear[Script Filter] Code 127: /bin/bash: cmd/search/search: No such file or directory`

Any ideas?

I'm using Alfred 4.0.5.

Thanks.

**Comment by drgrib** [comment]
I'm working on adding detailed instructions for how to do this in the readme but if you know how to open a terminal to the Bear workflow folder inside of Alfred, you can try running this command:

```
open cmd/search/search; open cmd/create/create; open cmd/link/link
```

and seeing if it resolves the issue.

**Comment by crsantos** [comment]
I'm not sure what happened here, but I reinstalled and it worked fine.

I think I had a lot of mixed installations of Bear workflows, and somehow they were Messe up. 🤷‍♂ 

Apologies for this.

And thank you so much for this.

> I'm working on adding detailed instructions for how to do this in the readme 

If I can help in some way, please say so

**Comment by drgrib** [comment]
Interesting. I'll hold off on documenting it until someone runs into the same problem then. Thanks for getting back to me on the issue.
