### ISSUE TITLE
Error when running on Monterey 12.3

### ISSUE THREAD

**Issue by dannyw** [drgrib/alfred-bear#50]
I just upgraded to the latest version of MacOS and unfortunately it broke these wonderful workflows. It appears that `/usr/bin/python` has been removed. Executing a command gives the following error: 

> [14:30:43.717] ERROR: Bear[Script Filter] Code 127: /bin/bash: /usr/bin/python: No such file or directory

`/usr/bin/python3` does exist, but pointing the Bear commands directly to that version still produces an error: 

> ModuleNotFoundError: No module named 'cPickle'

Any one else run into this? Any ideas on how to resolve? Thanks in advance.

**Comment by drgrib** [comment]
This is pretty confusing to me. The entire codebase is written in Go. There should be no Python involved. Are you sure you aren't running the Python based Alfred Bear workflow written by Chris Brown?
https://github.com/chrisbro/alfred-bear

I am still on Big Sur, personally, so I could be wrong.

**Comment by dannyw** [comment]
Hi @drgrib you're right, I'm running the version by Chris. Sorry for the wrong submission! I'll close this out.
