### ISSUE TITLE
Bear 2.0/Beta support request

### ISSUE THREAD

**Issue by themismlwn** [drgrib/alfred-bear#52]
Hey Drgrib, thank you so much for constantly updating this alfred-workflow and keeping it up for all of us to use. Its an amazing addition! Recently, i've been granted the use of Bear 2.0/private beta key and noticed that the workflow doesn't convert work for it.

On the surface I figured it would be an easy fix by going into the .go files and replacing the DBpath with the new SQL database used to store the notes, and replacing the xcallback urls found in the workflow scripts with the newer versions. 

Everything seemed to be working and the scripts were in fact working with bear 2.0, but i ran into a problem with the sql database, and despite changing dbpaths, I haven't been able to get the alfred workflow to find all the new notes created with bear 2.0

Below I've attached some screenshots of where i got the sql file path from and the new xcallback urls.

Hoping to see whether you could help out with the new sql database update, because I'm not a coder and its been frustrating me.

<img width="758" alt="Screenshot 2023-01-19 at 11 39 47 PM" src="https://user-images.githubusercontent.com/123126904/213586151-b2dcf5bd-5cc1-47c1-a369-045bf9e9648f.png">
<img width="828" alt="Screenshot 2023-01-19 at 11 41 18 PM" src="https://user-images.githubusercontent.com/123126904/213586358-c72883ef-103a-401f-8022-9fef7b0977d6.png">

Note: The new xcallback urls just add a "2" at the back of "bear"
Note: The new SQL Database uses 5 tags instead of 7

**Comment by drgrib** [comment]
Thanks for the heads up on this. Unfortunately, without sitting down with the new database myself and debugging, it is unlikely I'll figure out what needs to be changed. I can tell you upfront, it almost certainly isn't going to be a small fix because I'll need to build in backwards compatibility for people still using the old version. If I had to guess, it will probably take me weekend to work through.

If you can tell me how to get access to the beta, it would probably be best if I work on this before it is released.

**Comment by themismlwn** [comment]
Thanks for your reply! The beta is currently still in its private beta phase and is most likely going to remain so till they publicly release it somewhere near start of 2024. This is the [official forum to apply for the beta key](https://beta.bear.app/t/bear-2-beta-access-requests-07-11-2022/4894), however it might take some time to get a reply.

If you would like, I could forward you the email which granted me the access to the private beta, along with the download link for it. If that's something you're interested in, please reply with your email attached so I can get it done swiftly!

**Comment by drgrib** [comment]
Thanks for offering. After thinking about it, I think I should probably just wait for the public release. My development time outside of work is pretty limited and the database structure could change before release and even be changed to match exactly what it is now.

**Comment by dgdosen** [comment]
FYI - I was missing my BearSearch in Beta 2 (it's been taking a while!), so I upgraded the workflow.  I'm not familiar with Alfred Workflows, but was able to see the mirror of the project in the workflow folder.

I cloned the repo, made changes, built the project and copied over the workflow used by Bear.

I had to change:
- callback url (from 'bear' to 'bear2')
- the location to the folder for Bear2 Application Data 
- some sql calls - table and index name changes.

Working fine for me - I use it solely for search and have stopped using V1.
https://github.com/dgdosen/alfred-bear

**Comment by dgdosen** [comment]
Also - from looking at the Bear V2 beta forums, the V2 locations are all temporary.  The real launch of V2 will just use the V1 locations.  

So - this is a hack 🙂 for people using B2 only.

**Comment by drgrib** [comment]
That's what I suspected, which is why I didn't attempt to bake any of these locations into the workflow permanently. Thanks for the reference code in case they do actually change them.

**Comment by h-jia** [comment]
If you **only** want ver2.0 in use:
1. Simply add "2" in **all script** after "bear", i.e., `open "bear2://x-callback-url/create?{query}&show_window=yes&new_window=no&edit=no"`
2. cd /Applications and delete the original Bear.app (Do not use App Cleanr & Unistaller or others)
3. Move Bear.app (2.0 version) into /Applications
4. Empty trash

**Comment by rhazsolomon** [comment]
Hey!  Just did a quick run with the pre-release beta.  (This uses the correct paths as the public version).  Looks like the new database does not include the Z_7TAGS table.

**Comment by drgrib** [comment]
Thanks for the heads up. I'll debug this as soon as the new version goes live since I am a daily user of the workflow myself.

**Comment by K-JonDror** [comment]
According to the beta forums, the new version should be up tomorrow 🥳

**Comment by JonDror** [comment]
According to the beta forums, the new version should be up tomorrow 🥳

**Comment by EvanGrote** [comment]
Can confirm the v2 is now live

**Comment by drgrib** [comment]
I will merge in #54 either tonight or tomorrow morning when I have an open time window to debug if necessary. Based on testing comments on the request, I anticipate that it should just work.

**Comment by preems** [comment]
Appreciate your time and effort 🙏

**Comment by poohbers** [comment]
@drgrib thanks so much for updating! FYI, the download link in the new README is giving me this error

```xml
<Error>
<Code>NoSuchKey</Code>
<Message>The specified key does not exist.</Message>
<Key>130618635/33ba4883-f270-49cb-816e-bc233acbe239</Key>
<RequestId>DVTF2VG2ZV42KBSK</RequestId>
<HostId>sapgtNlYqwMDCXl5wD5w+fj8t4lIdkgDt9BqFDCWBCw90iEfnL3xjqnCtgYuZxjdIUf03EzlGG8=</HostId>
</Error>
```

**Comment by drgrib** [comment]
I just updated the release workflow file to fix an issue that caused tags to disappear from the Alfred query subtitles. My guess is you were trying to download during the window where I removed the old file. Please give it another try. If it is still a problem, please open a new issue.

Anyone who downloaded the file before 6 minutes ago will also want to redownload it for the fix.

Enjoy the new Bear with Alfred support everyone :)

**Comment by poohbers** [comment]
@drgrib working now! Thanks so much! I've really been missing this plugin while using the Bear beta

**Comment by chrisbarrettm** [comment]
Amazing. Thanks so much! Anyway to change setting so the note text is not a header?

**Comment by drgrib** [comment]
@chrisbarrettm I honestly have no idea what you are talking about. Please open a new issue and post a screenshot of what you are referring to.
