### ISSUE TITLE
Searching without the hotkey

### ISSUE THREAD

**Issue by ArlinJae** [drgrib/alfred-bear#55]
Hey @drgrib, I have a quick Q if you don't mind!

I was hoping to have Alfred automatically draw up results from my bear without me having to specifically put in `bs` at the starting of the query - could you please guide me through how to do that?

I have the workflow editor open in front of me and I was wondering if simply changing the script filter to a file action or a universal action would let me achieve what I'm gunning for?

Thanks a ton!

Cheers,
J

**Comment by drgrib** [comment]
I'm not sure if I understand why you would use a file action. But this is the hotkey trigger I have set up for my personal instance of the Bear workflow, tied to `bcs`. You should be able to open the workflow up and add a similar setup to your own instance.

<img width="193" alt="image" src="https://user-images.githubusercontent.com/3879367/227304586-8c2b423e-9032-4e17-8878-ec8c7ac664b7.png">

**Comment by drgrib** [comment]
This should keep you from having to type `bs`. The downside of this approach is that, as far as I know, you won't be able to access your previous queries in Alfred's query history, which has bitten me a few times. But overall, I find the convenience worth it.

**Comment by drgrib** [comment]
Closed as either resolved or unclear request.
