### ISSUE TITLE
Alfred Bear workflow may not work with Bear 2.x

### ISSUE THREAD

**Issue by Royaljerry** [drgrib/alfred-bear#58]
After updating Bear from 1.x to 2.x I experience the following behavior in the Alfred workflow.

---

**1. I type bs in order to find something in Bear:**

<img width="618" alt="alfred-1" src="https://github.com/drgrib/alfred-bear/assets/3762249/0b3ec7f7-d47b-403c-afc1-710a12f27181">

---

**2. As soon as I type a space and try to search for that phrase, Search Bear Notes disappears:***

<img width="614" alt="alfred-2" src="https://github.com/drgrib/alfred-bear/assets/3762249/57149113-0869-4ea6-933d-b5fbb78908bc">

---

_Could you confirm if this applies to you as well, or is it just me?_

---

* I definitely have at least one note containing the word “hello”

**Comment by drgrib** [comment]
Please follow the steps here to post the debug information you get:
https://github.com/drgrib/alfred-bear/issues/56#issuecomment-1546733678

**Comment by Royaljerry** [comment]
This is the error I get when running the workflow with debug:

```
[19:34:33.926] Logging Started...
[19:34:36.948] Bear[Script Filter] Queuing argument ''
[19:34:37.025] Bear[Script Filter] Script with argv '' finished
[19:34:37.028] ERROR: Bear[Script Filter] Code 2: panic: no such table: Z_7TAGS

goroutine 1 [running]:
main.main()
	/Users/credford/Dropbox/Alfred/Alfred.alfredpreferences/workflows/user.workflow.48B0F8E6-2BC8-4EB9-B35E-1DBB820AA8E7/cmd/search/main.go:29 +0x5e9
```

**Comment by drgrib** [comment]
Hmm. Are you sure you are running Bear 2.x? This sounds like an error you would get if you ran 1.x.

**Comment by drgrib** [comment]
Correction: are you sure you are using the latest release of `alfred-bear`? This sounds like an error you would get if you ran an old version.

Note that you are getting the exact same error as someone else who tried to run the old version on the new Bear:
https://github.com/drgrib/alfred-bear/issues/56#issuecomment-1546781824

**Comment by Royaljerry** [comment]
> Hmm. Are you sure you are running Bear 2.x? This sounds like an error you would get if you ran 1.x.

Absolutely.

<img width="285" alt="image" src="https://github.com/drgrib/alfred-bear/assets/3762249/13bcceb9-9b66-44c0-81db-32aec350b044">

**Comment by drgrib** [comment]
Please refer to my second comment.

**Comment by Royaljerry** [comment]
> Correction: are you sure you are using the latest release of `alfred-bear`? This sounds like an error you would get if you ran an old version.
> 
> Note that you are getting the exact same error as someone else who tried to run the old version on the new Bear: [#56 (comment)](https://github.com/drgrib/alfred-bear/issues/56#issuecomment-1546781824)

Gonna try to reinstall the existing workflow, download the current one, and install it, then I will report.

**Comment by Royaljerry** [comment]
OK Chris, case closed, the latest one works. Sorry about bothering you. Peace, love.

_Adam_

**Comment by drgrib** [comment]
No worries. Happy to hear the issue is solved. Having this here as a placeholder may help other people with the same issue.

**Comment by Royaljerry** [comment]
> No worries. Happy to hear the issue is solved. Having this here as a placeholder may help other people with the same issue.

Stil, I **love** this workflow. This is an awesome one.
