### ISSUE TITLE
Search failing with Bear2 update

### ISSUE THREAD

**Issue by JasperRobinson** [drgrib/alfred-bear#59]
Hi, 

'bs' was working just now with old Bear. I then updated to Bear2 and 'bs' stopped again [2023-07-21]. It looks the same as when the quarantine line [xattr -rd com.apple.quarantine cmd] needs to be run: 'bs' triggers the 'Search Bear Notes' prompt in the Alfred bar but disappears when you hit space and falls-back to a Finder-type of search. And 'bn' does still work to create a new Bear note. 

I've replaced the workflow with the current one from GitHub and run the quarantine command a couple of times, but this didn't bring the 'bn' search back. 

TIA, Jasper

![Bear Search](https://github.com/drgrib/alfred-bear/assets/8968646/a6870e9e-efe8-40cc-98b8-4bd7a5c68903)

**Comment by drgrib** [comment]
I suspect you are still using the old version of `alfred-bear`, tbh. But to confirm, please follow the steps here to post the debug information you get:
https://github.com/drgrib/alfred-bear/issues/56#issuecomment-1546733678

**Comment by JasperRobinson** [comment]
Thanks—I will do this next week and report back on #56, when I’m back at work on the problematic iMac. 

BTW, I think that your Bear Workflow was the new version because I got all the System Settings privacy & security stuff when trying to search after upgrading. 

Your new version on my home Mac works perfectly with Bear2

Cheers, Jasper

**Comment by drgrib** [comment]
Resolution in https://github.com/drgrib/alfred-bear/issues/56#issuecomment-1651448722
