### ISSUE TITLE
Error: "cmd/search/search: Bad CPU type in executable"

### ISSUE THREAD

**Issue by jamessimas** [drgrib/alfred-bear#64]
Hello,

**Problem:** When trying to search using this workflow, I type in "bs test". The workflow disappears after I start typing "test" and Alfred falls back to my default searches. This happens regardless of my search term; this is just what I was testing with today.

The debug log shows errors like this every time:

```
[13:00:07.332] Logging Started...
[13:00:57.506] Bear[Script Filter] Queuing argument 'test'
[13:00:57.526] Bear[Script Filter] Script with argv 'test' finished
[13:00:57.532] ERROR: Bear[Script Filter] Code 126: /Users/james_simas/Library/Caches/com.runningwithcrayons.Alfred/Workflow Scripts/0E686738-AF36-4F1A-9B8E-5BC579ED706A: line 1: cmd/search/search: Bad CPU type in executable
```

I'm running a MacBook Pro with an M1. Is this architecture supported?

Let me know if you need any additional info.

Thanks!

**Versions:**

* macOS: 13.5.1
* Alfred: 5.1.2 [2145]
* alfred-bear: v1.2.1

**Comment by drgrib** [comment]
I have the exact same specs as you do, down to the software versions and M1 MacBook Pro. It's the primary development environment.

Have you installed Rosetta? This executable type is necessary to keep the workflow compatible with Intel Macs:
https://github.com/drgrib/alfred-bear#-apple-silicon-macs

**Comment by jamessimas** [comment]
Ah, no, I haven't installed Rosetta. That would do it.

Thanks and apologies for missing that in the README.
