### ISSUE TITLE
Pressing SPACE after typing BS makes alfred-bear Workflow disappear

### ISSUE THREAD

**Issue by michaelfallik** [drgrib/alfred-bear#68]
Hello, I followed the instructions to install alfred-bear, including giving it all the permissions and installing Rosetta. Report steps:

1. Launch Alfred
2. Type BS
3. Hit the spacebar
3. Alfred searches for files instead

I attached a video of the repro. Running Mac Mini M1, Sonoma S14.1.1 (23B81)

Let me know if ii can provide you with more info. 

https://github.com/drgrib/alfred-bear/assets/68760057/471041e5-1f38-4edd-b109-2b881667296b

Appreciate any help!

**Comment by drgrib** [comment]
I've updated the [installation instructions](https://github.com/drgrib/alfred-bear/blob/master/README.md#install). Have you followed all these steps?

If you already have and it still isn't working, please provide the debug log you get by following these steps:
https://github.com/drgrib/alfred-bear/issues/56#issuecomment-1546733678

**Comment by michaelfallik** [comment]
Thank you. I reinstalled the app, following your instructions and it worked. I believe the issue was that once I typed BS for the first time I accidentally denied the search permissions.

**Comment by drgrib** [comment]
Glad to hear that worked.
