### ISSUE TITLE
Infinite wait state

### ISSUE THREAD

**Issue by kyle-hong** [drgrib/alfred-bear#69]
Searching for notes in Bear using `bs` results in an infinite search with no results, as shown in the following debugging image.
Just out of curiosity, I've uninstalled and reinstalled Workflow and am seeing the same thing.

Note that this is the same for `bn` as well as `bs`

![image](https://github.com/drgrib/alfred-bear/assets/92346462/abcb1ab7-8c0b-42e9-a986-0f25a4f75caf)

**Comment by drgrib** [comment]
Can you follow the steps here? https://github.com/drgrib/alfred-bear/issues/68#issuecomment-1816460797

**Comment by kyle-hong** [comment]
I use icloud for Alfred syncing and the workflow hasn't worked since I enabled icloud's advanced data protection.

I moved the Alfred Syncing File to Local and the workflow worked fine.

It was an issue caused by icloud's advanced data feature. Since this is not an issue with the feature itself, I think we can close the issue.

**Comment by drgrib** [comment]
Thanks for the update. I think I remember iCloud causing similar issues for me with Alfred in general years ago. In case you are looking for an alternative syncing method, I have used both Dropbox and Google Drive successfully for years at a time each.
