### ISSUE TITLE
Please add the github sponsorship.

### ISSUE THREAD

**Issue by Hansanghyeon** [drgrib/alfred-bear#71]
매달은 아니더라도 나는 일회성으로 당신을 후원할 생각이있습니다. 정말 좋은 소프트웨어에 감사합니다.

I'm thinking of sponsoring you on a one-off basis, if not every month. Thank you for the really good software.

**Comment by drgrib** [comment]
Sure thing. Thanks for the suggestion and the offer to contribute. I've created it here:
https://github.com/sponsors/drgrib

Do you have any recommendations or examples on how I should make this visible on my profile? Or do you think just having it set up is enough for people to find it if they are interested?

**Comment by drgrib** [comment]
Oh I see on someone else's page, the "Sponser" button appears automatically. Is this on my profile now? I can't see it myself to verify, even in incognito mode. I guess it requires being signed in to another account.

![image](https://github.com/drgrib/alfred-bear/assets/3879367/48ff88fd-bed7-4de1-b13c-c42278b1a6dc)

**Comment by Hansanghyeon** [comment]
repo > settings > Features > Sponsorhips

<img width="877" alt="image" src="https://github.com/drgrib/alfred-bear/assets/42893446/c8025563-fe61-4676-a7eb-2e94dbe6718a">

This way, you can sponsor the repo! wow

**Comment by drgrib** [comment]
Thanks!

**Comment by Hansanghyeon** [comment]
sponsorship button has appeared, but it takes you to the profile. I misunderstood. I need to enable sponsorship from the profile. I'm sorry for any confusion. 🥲

**Comment by drgrib** [comment]
You mean it takes you to https://github.com/sponsors/drgrib? If so, isn't that the expected behavior? I'm confused what you expected to happen.

**Comment by Hansanghyeon** [comment]
<img width="385" alt="image" src="https://github.com/drgrib/alfred-bear/assets/42893446/b343787f-d101-43c9-ad8a-b9bcffd60745">

There was no sponsor button

**Comment by drgrib** [comment]
So what did you mean when you said "sponsorship button has appeared"? Are you talking about the one on the repo?
