### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by lt-rawlins** [drgrib/alfred-bear#72]
Can you include a license file, so that people know what is and is not permissible with this workflow?

**Comment by drgrib** [comment]
Any suggestions? I've never thought about it.

**Comment by lt-rawlins** [comment]
GPL Version 3 is my general goto license. But I'm one of those free software weirdo's 🤣

**Comment by drgrib** [comment]
Added in 74a14f053245184e423880b9fd9dc72adb7b7bcd

After some research, I've gone with MIT, as someone who has worked at several commercial companies and empathizes with SWEs just trying to get their job done without jumping through licensing hoops. More generally, I view capitalism as deeply vulnerable to damning flaws but also the best economic system currently on offer.
