### ISSUE TITLE
Get the link to that note via a hotkey (shift enter, option enter, etc.)

### ISSUE THREAD

**Issue by LYTWilson** [drgrib/alfred-bear#73]
Curious to ask if it would be possible to make a hotkey to copy the link to the note (bear://x-callback-url/open-note?id=111016E4-AC03-46A7-96D5-EDE81646F666) in some format like this via the workflow. 

I think that would be very convenient, as I guess it could easily be pasted into something relevant, like a task manager or calendar event. That makes thing very simple. I've seen a workflow called [search notes](https://github.com/sballin/alfred-search-notes-app) could do it in apple notes. I guess it could be possible in this workflow? 

Curious if others had a similar request in their daily workflow.

**Comment by drgrib** [comment]
Hold cmd+shift while selecting the note.
![Untitled](https://github.com/drgrib/alfred-bear/assets/3879367/ed2206d4-d506-4d15-8bbd-720d80497eaf)
