### ISSUE TITLE
Considering upload this workflow to Alfred Gallery？

### ISSUE THREAD

**Issue by 0ptimista** [drgrib/alfred-bear#75]
https://alfred.app/submit/

for the updating  convenience

**Comment by drgrib** [comment]
As far as I can tell, that link just points to the forums, where I already made a post when I first made the workflow:
https://www.alfredforum.com/topic/13748-new-bear-alfred-workflow/#comment-70632

If you find a more direct way to add this to the Alfred Gallery, please reopen and tell me.
