### ISSUE TITLE
The commands don't work

### ISSUE THREAD

**Issue by cmkaya** [drgrib/alfred-bear#76]
Hello,

I have been trying to use your workflow but I haven't been successful. Maybe I have been missing something. 

When I try to search, it directs me to internet search:

<img width="746" alt="SCR-20241010-rpvn" src="https://github.com/user-attachments/assets/d3c8dcbf-0161-4904-a8b1-b94b962b53a7">

I executed the command where you explained for authorization.

Am I doing something wrong?

**Comment by drgrib** [comment]
Have you already followed all the [Install](https://github.com/drgrib/alfred-bear?tab=readme-ov-file#install) steps?

**Comment by cmkaya** [comment]
@drgrib Yes, I followed except of installing rosetta. My Mac is m1

**Comment by drgrib** [comment]
You have to install Rosetta. It won't work on M1 Macs without that because it is an Intel binary to stay compatible with older Macs. Please try that and let me know

**Comment by drgrib** [comment]
Closing as user error (did not install Rosetta as instructed in install steps).

**Comment by cmkaya** [comment]
@drgrib 
Thanks it is resolved.
